[package]
name = "warp_test"
version = "0.1.0"
authors = ["Erutuon <5840197+Erutuon@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.4", features = ["macros"] }
warp = "0.2.0"
markup = "0.4.1"
regex = { version = "1.3.0", features = ["std"]}
once_cell = "1.0.2"
rlua = "0.16.3"
unicode-segmentation = "1.3.0"